# Generated by Django 3.2.21 on 2023-11-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model01_id', models.CharField(max_length=250)),
                ('field_01', models.CharField(max_length=255)),
            ],
        ),
    ]
